sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - dev # build master branch only
before_script:
before_install: 
  - npm i -S hexo-generator-search hexo-generator-json-content
  - npm i -S hexo-renderer-stylus
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: dev
  local-dir: public
